import metamask from './metamask.png';
import walletConnectIcon from './walletConnectIcon.svg';
import coinbaseWalletIcon from './coinbaseWalletIcon.svg';
import nightElfIcon from './nightElf.png';
import union from './union.svg';
import arrow from './arrow.svg';
import success from './success.svg';
import tableEmpty from './tableEmpty.svg';
import sandGlass from './sandGlass.svg';
export { metamask, walletConnectIcon, coinbaseWalletIcon, nightElfIcon, union, arrow, success, tableEmpty, sandGlass };
