export const InfoIcons = {
  website: 'official-website',
  github: 'github',
  discord: 'discord',
  twitter: 'twitter',
  reddit: 'reddit',
  telegram: 'telegram',
  ins: 'ins',
  facebook: 'facebook',
  owner: 'owner',
  whitelist: 'whitelist',
};

export const Icons = {
  appendix: 'appendix',
  user: 'user',
  overview: 'overview',
  projects: 'projects',
  create: 'create',
  idoInfo: 'idoInfo',
  stagingMethod: 'stagingMethod',
  team: 'team',
  modifyInfo: 'modifyInfo',
  share: 'share',
  search: 'search',
  lockInfo: 'lockInfo',
  uploadIcon: 'upload-icon',
  menuIcon: 'menu-icon',
  closeIcon: 'close-icon',
  infoIcon: 'info-icon',
  successIcon: 'success-icon',
};
